version: 2
jobs:
  build:
    working_directory: /go/src/github.com/juanaveragedeveloper/wrk
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get -u github.com/mitchellh/go-homedir
      - run: go get -u github.com/spf13/cobra
      - run: go get -u github.com/spf13/viper
      - run:
          name: run build
          command: |
            go build -v
      - run:
          name: run tests
          command: |
            go fmt ./...
            go test -v ./...
  deploy:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/juanaveragedeveloper/wrk
    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run: go get -u github.com/stevenmatthewt/semantics
      - run: go get -u github.com/mitchellh/go-homedir
      - run: go get -u github.com/spf13/cobra
      - run: go get -u github.com/spf13/viper
      - run: go get -u github.com/inconshreveable/mousetrap
      - run:
          name: cross compile
          command: |
            gox -os="linux darwin windows" -arch="amd64" -output="dist/spotifycli_{{.OS}}_{{.Arch}}"
            cd dist/ && gzip *
      - add_ssh_keys
      - run:
          name: create release
          command: |
            tag=$(semantics --output-tag)
            if [ "$tag" ]; then
              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag dist/
            else
              echo "The commit message(s) did not indicate a major/minor/patch version."
            fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
